package main

import (
	"crypto/ed25519"
	"crypto/rand"
	"encoding/base64"
	"strings"
	"testing"

	"kton.dev/plankton/core"
	"kton.dev/plankton/registry"
)

// addFoton signs and ingests a minimal foton (in -> protocol -> out) with no descriptor (so the
// §6.2 ref check is a no-op).
func addFoton(t *testing.T, r *registry.Registry, kind, inName, inHex, outName, outHex string) {
	addFotonKID(t, r, kind, inName, inHex, outName, outHex, "k")
}

// addFotonKID is addFoton with an explicit declared keyid, so a test can plant an attacker-authored
// keyid string in the envelope's Signatures[0].KeyID (the RDF signer field).
func addFotonKID(t *testing.T, r *registry.Registry, kind, inName, inHex, outName, outHex, keyid string) {
	t.Helper()
	st := map[string]any{
		"_type":         "https://in-toto.io/Statement/v1",
		"subject":       []any{map[string]any{"name": outName, "digest": map[string]any{"sha256": outHex}}},
		"predicateType": core.PredicateFoton,
		"predicate": map[string]any{
			"inputs":   []any{map[string]any{"name": inName, "digest": map[string]any{"sha256": inHex}}},
			"protocol": map[string]any{"kind": kind, "ref": "sha256:proto"},
		},
	}
	payload, err := core.CanonValue(st)
	if err != nil {
		t.Fatal(err)
	}
	_, priv, _ := ed25519.GenerateKey(rand.Reader)
	sig := ed25519.Sign(priv, core.PAE(core.PayloadType, payload))
	env := core.Envelope{PayloadType: core.PayloadType, Payload: base64.StdEncoding.EncodeToString(payload)}
	env.Signatures = append(env.Signatures, struct {
		KeyID string `json:"keyid"`
		Sig   string `json:"sig"`
	}{KeyID: keyid, Sig: base64.StdEncoding.EncodeToString(sig)})
	if _, _, err := r.Add(env); err != nil {
		t.Fatalf("add %s foton: %v", kind, err)
	}
}

// TestExportRDF: the lineage renders as PROV, the join node (an output that is another foton's input)
// carries both prov:wasGeneratedBy and prov:used, and --lineage restricts output to a subset.
func TestExportRDF(t *testing.T) {
	r, err := registry.Open(t.TempDir())
	if err != nil {
		t.Fatal(err)
	}
	raw := strings.Repeat("11", 32)
	prepared := strings.Repeat("22", 32)
	model := strings.Repeat("33", 32)
	addFoton(t, r, "qc", "raw.csv", raw, "prepared.csv", prepared)
	addFoton(t, r, "fit", "prepared.csv", prepared, "model.json", model)

	all, err := buildRDF(r, "", nil)
	if err != nil {
		t.Fatal(err)
	}
	if n := strings.Count(all, "prov:wasGeneratedBy pk:"); n != 2 {
		t.Fatalf("want 2 outputs (prepared, model), got %d:\n%s", n, all)
	}
	// the JOIN: prepared.csv is generated by the qc foton AND used by the fit foton
	if !strings.Contains(all, "pk:"+prepared+" a prov:Entity") {
		t.Fatalf("the shared output must be an entity:\n%s", all)
	}
	if !strings.Contains(all, "prov:used pk:"+prepared) {
		t.Fatalf("the fit foton must prov:use the shared output:\n%s", all)
	}

	// SUBSET: the lineage of `prepared` is just the qc foton (1 output entity); the lineage of `model`
	// is the whole chain (2).
	sub, err := buildRDF(r, "sha256:"+prepared, nil)
	if err != nil {
		t.Fatal(err)
	}
	if n := strings.Count(sub, "prov:wasGeneratedBy pk:"); n != 1 {
		t.Fatalf("prepared's lineage should be the qc foton alone, got %d outputs:\n%s", n, sub)
	}
	full, _ := buildRDF(r, "sha256:"+model, nil)
	if n := strings.Count(full, "prov:wasGeneratedBy pk:"); n != 2 {
		t.Fatalf("model's lineage should be the whole chain (2 outputs), got %d", n)
	}
}

// TestExportRDF_KeyIDInjection: the declared signer keyid (Signatures[0].KeyID) is attacker-authored and
// is emitted even on the unverified path (nk:claimedSigner). A crafted keyid carrying Turtle syntax must
// NOT inject triples; agentNode drops any non-hex keyid so the whole attribution is omitted. A clean hex
// keyid still renders as agent:<hex>. (RDF-injection round-2 H-b, signer-field sibling of the pkNode guard.)
func TestExportRDF_KeyIDInjection(t *testing.T) {
	r, err := registry.Open(t.TempDir())
	if err != nil {
		t.Fatal(err)
	}
	inHex := strings.Repeat("11", 32)
	poisonOut := strings.Repeat("22", 32)
	cleanOut := strings.Repeat("33", 32)

	// a keyid that, interpolated raw into Turtle, would close the triple and inject a forged attribution
	poison := "x .\n_:inj prov:wasAttributedTo agent:attacker .\nagent:y"
	addFotonKID(t, r, "qc", "raw.csv", inHex, "poison.csv", poisonOut, poison)
	addFotonKID(t, r, "qc", "raw.csv", inHex, "clean.csv", cleanOut, "0123456789abcdef")

	// nil trustKeys -> nothing verifies -> both take the claimedSigner (unverified) path
	out, err := buildRDF(r, "", nil)
	if err != nil {
		t.Fatal(err)
	}
	if strings.Contains(out, "attacker") || strings.Contains(out, "_:inj") {
		t.Fatalf("injected triple leaked into the Turtle output:\n%s", out)
	}
	// the poison keyid is dropped entirely (non-hex) -> no claimedSigner for it
	if strings.Contains(out, "nk:claimedSigner agent:x") {
		t.Fatalf("poison keyid was emitted instead of dropped:\n%s", out)
	}
	// the clean hex keyid still renders as a proper agent node
	if !strings.Contains(out, "nk:claimedSigner agent:0123456789abcdef ;\n    nk:signerVerified false") {
		t.Fatalf("clean hex keyid should render as an agent node:\n%s", out)
	}
}
