package claim_test

// vectors_test.go freezes the nekton cross-implementation contract (SPEC §7). It reads each frozen
// vector in ../testdata (regenerated by `go run ./testdata/gen`), recomputes the claim id and asserts
// the FIXED value, verifies the DSSE signature against the PUBLISHED public key, and rejects a
// one-byte-tampered payload. Any drift here CI-fails - exactly as plankton's reference/core/core_test.go
// TestGoldenVectors does one layer down. Update by rerunning gen and pasting the new ids (and SPEC §7).

import (
	"encoding/base64"
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"kton.dev/nekton/claim"
	"kton.dev/plankton/core"
)

const td = "../testdata/"

func readEnv(t *testing.T, name string) core.Envelope {
	t.Helper()
	b, err := os.ReadFile(filepath.Join(td, name))
	if err != nil {
		t.Fatal(err)
	}
	var e core.Envelope
	if err := json.Unmarshal(b, &e); err != nil {
		t.Fatal(err)
	}
	return e
}

func pubKey(t *testing.T, name string) []byte {
	t.Helper()
	b, err := os.ReadFile(filepath.Join(td, name))
	if err != nil {
		t.Fatal(err)
	}
	k, err := core.ParsePublicKeyHex(strings.TrimSpace(string(b)))
	if err != nil {
		t.Fatal(err)
	}
	return k
}

// The frozen SPEC §7 vectors: DSSE file, its signer's published .pub, and the FIXED claim id.
type vector struct {
	dsse, pub, wantID string
}

var vectors = []vector{
	{"reviewed.dsse.json", "reviewer.pub", "sha256:9913d1c7d5460ee09759eccfe77eccdcf3d1b5458fc0c9c9e5577532e545c0ab"},
	{"delegate.dsse.json", "chair.pub", "sha256:cf18b528cabb0a033c3dcb76b56b7ac10aaa02a0c10b5fc2f21b4b022f048969"},
	{"sameas.dsse.json", "curator.pub", "sha256:ed75d8ad311a904cc9408cdcd74b3045e7e8e9fdee5f00d01449c2273aa01b36"},
	{"foton-subject.dsse.json", "reviewer.pub", "sha256:f74b5a76b02f7dd9d016d591459a35c4d848d3e7baf2269ebd448d492455792b"},
}

// TestGoldenVectors: every frozen vector recomputes to its FIXED claim id and verifies against its
// published key. A second implementation MUST reproduce these ids from the *.statement.json sources.
func TestGoldenVectors(t *testing.T) {
	for _, v := range vectors {
		t.Run(v.dsse, func(t *testing.T) {
			env := readEnv(t, v.dsse)
			_, payload, err := claim.ParseEnvelope(env)
			if err != nil {
				t.Fatalf("parse: %v", err)
			}
			if got := claim.ClaimID(payload); got != v.wantID {
				t.Fatalf("claim id drift:\n got %s\nwant %s", got, v.wantID)
			}
			if ok, err := env.Verify(pubKey(t, v.pub)); err != nil || !ok {
				t.Fatalf("published key must verify %s (ok=%v err=%v)", v.dsse, ok, err)
			}
		})
	}
}

// TestVectorsRejectTamper: a one-byte flip of any vector's payload breaks verification (SPEC §4/§7).
func TestVectorsRejectTamper(t *testing.T) {
	for _, v := range vectors {
		t.Run(v.dsse, func(t *testing.T) {
			env := readEnv(t, v.dsse)
			raw, err := base64.StdEncoding.DecodeString(env.Payload)
			if err != nil {
				t.Fatal(err)
			}
			raw[10] ^= 0x01
			env.Payload = base64.StdEncoding.EncodeToString(raw)
			if ok, _ := env.Verify(pubKey(t, v.pub)); ok {
				t.Fatal("a one-byte-tampered payload must not verify")
			}
		})
	}
}

// TestVectorsWrongKeyRejected: each vector must NOT verify under a different vector's key - the
// signer identity is load-bearing (four-eyes / governance separation). reviewed & foton-subject share
// the reviewer key by design; every cross-signer pair must fail.
func TestVectorsWrongKeyRejected(t *testing.T) {
	env := readEnv(t, "delegate.dsse.json") // signed by chair
	if ok, _ := env.Verify(pubKey(t, "curator.pub")); ok {
		t.Fatal("curator key must not verify the chair's delegate claim")
	}
	if ok, _ := env.Verify(pubKey(t, "reviewer.pub")); ok {
		t.Fatal("reviewer key must not verify the chair's delegate claim")
	}
}

// TestFotonSubjectSplice: the cross-layer vector's subject is a plankton foton hash, resolvable by a
// nekton consumer holding no plankton component. Its subject Key() MUST equal the frozen plankton foton
// id (reference/testdata TestGoldenVectors), so `nekton about <foton id>` splices the two layers by hash.
func TestFotonSubjectSplice(t *testing.T) {
	const plaktonFotonID = "sha256:5da55d7885d87097e5decf17d7edf6e49597a655f401249cca66bd77a17121f1"
	env := readEnv(t, "foton-subject.dsse.json")
	st, _, err := claim.ParseEnvelope(env)
	if err != nil {
		t.Fatal(err)
	}
	if len(st.Subject) != 1 {
		t.Fatalf("want 1 subject, got %d", len(st.Subject))
	}
	if k := st.Subject[0].Key(); k != plaktonFotonID {
		t.Fatalf("cross-layer splice broken: subject key %s != plankton foton id %s", k, plaktonFotonID)
	}
}
